### ISSUE TITLE
Wrong way around? with Mediachase...CurrencyFormatter.ConvertCurrency

### ISSUE THREAD

**Issue by LucGosso** [jstemerdink/EPi.Libraries.Commerce.ExchangeRates#1]
Hi Jeroen! Nice plugin. 

I had to change the logic of converting to make it work. How do your convert?

When using 
`Mediachase.Commerce.Shared.CurrencyFormatter.ConvertCurrency(workingCurrencyPrice,workingCurrency), new Currency(tryCurrency));`

Before in the currency table I had on 1 SEK = EUR 0.1111 and with your plugin 1 SEK = EUR 9.46

To make it work i did a work around: 

```
//crasy thing to make the EPi.Libraries.Commerce.ExchangeRates to work
Money displayPrice = Mediachase.Commerce.Shared.CurrencyFormatter.ConvertCurrency(new Money(workingCurrencyPrice, tryCurrency), new Currency(workingCurrency));//other way around
displayPrice = new Money(displayPrice.Amount, new Currency(tryCurrency)); // becauce the currency get twisted
```

Would be nice to have it configuable? 

Regards!

**Comment by jstemerdink** [comment]
Hi, am not sure what you mean? I just ran it in a Quciksilver instance and when I look in the commerce manager at the exchange rates for SEK, I see that the value for the euro is 0.1121. When I go to the Euro it says 0.1059 for the SEK.

Or do you mean displaying it in the FrontEnd?

**Comment by LucGosso** [comment]
Strange, in my instance the exchange rates for SEK, I see that the value for the euro is 9.46 (after runing your code). Well, i check your code and see if it is some config that i have different...

**Comment by jstemerdink** [comment]
I have had another look, and it is indeed the other way around. Dunno why I did not see that this afternoon. As I said in my blog, it was a piece of Quicksilver that I based it on. I'll file the bug with Quicksilver as well. I'll create a fix release, and upload it to the EPiServer feed. Thanx for pointing it out.

**Comment by jstemerdink** [comment]
The package has finally been approved this week, so you can find it in the feed.

**Comment by LucGosso** [comment]
Important! ok, the conversion is right now. BUT, it adds everytime instead of updating. After running the job several times, my EURO has over 100 rates, USD is several time for example.

Downloaded from Episerver Nuget. version 1.0.1.0
