### ISSUE TITLE
Configurable which currency do update

### ISSUE THREAD

**Issue by LucGosso** [jstemerdink/EPi.Libraries.Commerce.ExchangeRates#2]
Hi Jeroen, 

I have downloaded the plugin thru nuget.episerver.com with fixer provider. 

Would it be possible to make it configurable which currency to download, instead of downloading all 32 of them? Not important but nice to have.

Regards

**Comment by jstemerdink** [comment]
I guess it is possible, but why would you want that? All currencies are,by default anyway, available in Commerce. The response from the service is not that big that it would be an issue, or is it? So why not have them all available? It would mean one extra configuration step if you would have to chose which currencies to import.

**Comment by LucGosso** [comment]
By default, my instance didnt have all currencies, thats why. Maybe deleted just because they didn't want to display all currencies on Front end. An config for add or only update would be nice. Just a relfection =)

**Comment by jstemerdink** [comment]
Ah ok, though I think deleting the currencies in the backend is not really a good idea just for frontend purposes, as you normally would only list the currencies for the active market in the frontend. Also just a reflection :) 
I'll have a look when I got some more time if it can be done, and done in a way that's not too much hassle for users
