### ISSUE TITLE
Version 1.0.1.0 adds instead of updating

### ISSUE THREAD

**Issue by LucGosso** [jstemerdink/EPi.Libraries.Commerce.ExchangeRates#3]
Runing the job adds everytime instead of updating. After running the job several times, my EURO has over 100 rates, USD is several time for example.

Downloaded from Episerver Nuget. version 1.0.1.0

**Comment by jstemerdink** [comment]
Yes I noticed that behavior. Updating was in an earlier version, well the code was anyway, but it never worked and just added a new row. I have created a feature branch where I delete all previous versions first, than add a new row. But ... this also does not work, though I see all rows have gone from the dto when I debug, they still appear in the Commerce Manager, along with the new ones. I'll check with the Commerce team at EPiServer what's going on.

**Comment by jstemerdink** [comment]
The update is working now. Will be on NuGet when it's approved.

**Comment by jstemerdink** [comment]
Apparently deleting an item is not possible. So When deleting all items, the new one got added, as there were no items. But when saving the dto, the deleted items are back.

**Comment by LucGosso** [comment]
Working like it supposed now in version 1.1 _Thumbs up_
